name: Scheduled AutoPkg Workflow

on:
  schedule:
    - cron: "0 0 * * *"  # Adjust schedule as needed
  workflow_dispatch:  # Enables manual triggering

jobs:
  autopkg-run:
    runs-on: macos-latest
    env:
      MUNKI_VERSION: 6.6.5
      MUNKI_EXPLICIT_VERSION: 6.6.5.4711
      APKG_VERSION: 2.7.3 # 'AUTOPKG_' gets injected as an env var
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for accurate diffs

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            metadata_cache.json
          key: cache-${{ hashFiles('uv.lock') }}

      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174
        with:
          version: "latest"
          enable-cache: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install AutoPkg
        uses: joncrain/macos-pkg-install@v1.0
        with:
          pkg_url: https://github.com/autopkg/autopkg/releases/download/v${{ env.APKG_VERSION }}/autopkg-${{ env.APKG_VERSION }}.pkg

      - name: Install Munki
        uses: joncrain/macos-pkg-install@v1.0
        with:
          pkg_url: https://github.com/munki/munki/releases/download/v${{ env.MUNKI_VERSION }}/munkitools-${{ env.MUNKI_EXPLICIT_VERSION }}.pkg

      - name: Configure AutoPkg
        run: |
          AUTOPKG_DIR="${{ github.workspace }}/AutoPkg"
          MUNKI_DIR="${{ github.workspace }}/Munki"

          defaults write com.github.autopkg CACHE_DIR "${AUTOPKG_DIR}/Cache"
          defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool TRUE
          defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"
          defaults write com.github.autopkg MUNKI_REPO "${MUNKI_DIR}"
          defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "${AUTOPKG_DIR}/Overrides"
          # defaults write com.github.autopkg RECIPE_REPO_DIR "${AUTOPKG_DIR}/RecipeRepos"
          defaults write com.github.autopkg RECIPE_SEARCH_DIRS -array-add "${AUTOPKG_DIR}/Recipes"

          mkdir "${MUNKI_DIR}/pkgs"

      - name: AutoPkg Repo Add
        run: |
          cat "${{ github.workspace }}/AutoPkg/repo_list.txt" | xargs autopkg repo-add

      - name: Determine Recipe List
        id: recipe_list
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD AutoPkg/Overrides/*.recipe)

          if [[ ! -z "${CHANGED_FILES}" ]]; then
            TEMP_RECIPE_LIST=$(mktemp)
            RECIPE_LIST=$(echo "${CHANGED_FILES}" | grep 'AutoPkg/Overrides/.*\.recipe' | sed 's/AutoPkg\/Overrides\///g' | jq -R -s 'split("\n")[:-1]')
            echo "${RECIPE_LIST}" > "${TEMP_RECIPE_LIST}"

            echo "RECIPE_LIST=${TEMP_RECIPE_LIST}" >> $GITHUB_OUTPUT
          else
            echo "RECIPE_LIST=AutoPkg/recipe_list.json" >> $GITHUB_OUTPUT
          fi

      - name: Run AutoPkg
        run: |
          uv run autopkg-run \
            --cache-file metadata_cache.json \
            --log-file autopkg_runner.log \
            --recipe-list "${{ steps.recipe_list.outputs.RECIPE_LIST }}"

      - name: Commit Munki Changes
        run: |
           git add Munki/*
           git commit -m "Adding updated Munki files"
           git push

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autopkg-run-artifacts
          path: |
            AutoPkg/Cache/**/*receipt*
            autopkg_runner.log
            metadata_cache.json
